server:
  port: 6001
spring:
  application:
    name: springCloudEureka
  profiles:
    active: springCloudEureka
security:
  basic:
    enabled: true #开启认证
  user:
    name: user
    password: 123456
eureka:
  instance:
    hostname: springCloudEureka
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://user:123456@127.0.0.1:6002/eureka